apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    keycloak.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - keycloak.10.0.0.232.nip.io
  rules:
  - host: keycloak.10.0.0.232.nip.io
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080

